/** Plain-language notes for activity-log entries (template-based, not LLM). */

const KEY_NOTES: Record<string, string> = {
  n: "Store number of periods in n.",
  i: "Store annual interest rate in i (as a percent).",
  PV: "Store present value in PV.",
  PMT: "Store payment in PMT.",
  FV: "Store future value in FV.",
  ENTER: "Stack lift — duplicate X into Y.",
  "f ENTER": "PREFIX — show full mantissa of X until the next operation.",
  "g ENTER": "LSTx — recall last X used in a binary operation.",
  CHS: "Change sign.",
  "g CHS": "DATE — combine days in Y with date in X (M.DY or D.MY).",
  EEX: "Enter exponent (scientific notation).",
  "g EEX": "ΔDYS — days between dates; x↔y for 30/360.",
  "f y^x": "Bond PRICE — clean price in X, accrued interest in Y, PV updated.",
  "f 1/x": "Bond YTM — yield in X and i, accrued interest in Y.",
  "g y^x": "√x — square root of X.",
  "g 1/x": "e^x — natural exponential of X.",
  "f %T": "Straight-line depreciation for year in X.",
  "f Δ%": "Sum-of-years-digits depreciation for year in X.",
  "f %": "Declining-balance depreciation for year in X.",
  "f AMORT": "Amortization schedule entry (via n key with f).",
  "f INT": "Simple interest (360-day year) in X; |PV| in Y for total with +; R↓ then x↔y for 365-day.",
  "f NPV": "Net present value from stored cash flows.",
  "f IRR": "Internal rate of return from stored cash flows.",
  "f RND": "Round X to current display format.",
  "g CFo": "Clear cash-flow registers; store CF₀.",
  "g CFj": "Store next cash-flow amount.",
  "g Nj": "Store repeat count for last cash flow.",
  "g DATE": "Same as g CHS — calendar date from days and date.",
  "g BEG": "Payment mode: beginning of period.",
  "g END": "Payment mode: end of period.",
  "g 4": "Date format D.MY; display set to 6 decimal places.",
  "g 5": "Date format M.DY; display set to 6 decimal places.",
  "g 0": "Mean of x (x̄).",
  "g 1": "Linear-estimation correlation coefficient r.",
  "g 2": "Mean of y (ȳ).",
  "g 3": "Factorial n! (integers 0–69).",
  "g 6": "Weighted mean x̄w.",
  "g 9": "Program memory remaining (0 — programming not implemented).",
  "g .": "Sample standard deviation sx; press again (or x↔y) for sy.",
  "g CLx": "Count Σ+ pairs where x = 0.",
  "g SST": "Backspace last digit while entering a number.",
  "g x↔y": "x ≤ y test — 1 if true, else 0.",
  "g Σ+": "Remove last Σ+ pair (Σ−).",
  "Σ+": "Add X and Y to statistics (Σ+).",
  STO: "Store prefix — next digit selects register 0–9.",
  RCL: "Recall prefix — next digit selects register 0–9.",
  f: "Toggle f shift (web: stays active until cleared or used).",
  g: "Toggle g shift (web: stays active until cleared or used).",
  "f CLx": "Clear financial registers (FIN).",
  "f SST": "Clear statistics registers (Σ).",
  "f x↔y": "Clear program steps (no-op — programming not implemented).",
  "f R↓": "Clear cash-flow registers.",
};

/** Return a short note for a resolved key label, if we have one. */
export function describeKeystroke(keyLabel: string): string | null {
  return KEY_NOTES[keyLabel] ?? null;
}
